log:
  level: info

plugins:
  - tag: main
    type: forward
    args:
      concurrent: 3
      upstreams:
        - tag: google_doh
          addr: "https://8.8.8.8/dns-query"
          max_conns: 3
        - tag: google_dot
          addr: "tls://8.8.4.4"
          enable_pipeline: true
          max_conns: 3
        - tag: quad9_doh
          addr: "https://9.9.9.11/dns-query"
          max_conns: 3
        - tag: quad9_dot
          addr: "tls://9.9.9.11"
          enable_pipeline: true
          max_conns: 3

  - tag: "http_server"
    type: "http_server"
    args:
      entries:
        - path: /dns-query
          exec: main
      src_ip_header: "X-Forwarded-For"
      listen: :8080
      idle_timeout: 10